Repository AY2324S1-CS2103T-T14-2/tp, pull requests merged in 2023-11, with the labels that each got.

#160 Update Edit command related tests
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/RecordCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High

#162 Improve implementation of Age
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/patient/Age.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/patient/AgeTest.java
  src/test/java/seedu/address/model/patient/BirthdayTest.java
Labels: type.Bug, priority.Medium

#163 Create test for Assign Command feature
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RecordCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RecordCommandParserTest.java
  src/test/java/seedu/address/model/patient/RecordTest.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.High

#164 Implement JSON storage for patient records
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/patient/Record.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/model/patient/UniqueRecordListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
Labels: priority.High

#168 Editing documentations
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/jar.png
Labels: priority.Low

#171 Update UI and UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/ug/helpMessage.png
  docs/images/ug/listPatients.png
  docs/index.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/RecordCard.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientListPanel.css
  src/main/resources/view/RecordCard.css
  src/main/resources/view/RecordCard.fxml
  src/main/resources/view/ResultDisplay.css
Labels: priority.High

#173 Fix bug whereby UI does not update with new Record field values when record is edited
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RecordCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/model/patient/Record.java
  src/main/java/seedu/address/ui/RecordCard.java
Labels: type.Bug, priority.Medium

#176 Update UserGuide.md to allow user to download latest release
  docs/UserGuide.md
Labels: priority.High

#225 Fix failing test cases
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/patient/Record.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: priority.High

#226 Fix bug with sort and added testing for assign and sort
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/model/patient/Name.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/patient/AgeTest.java
  src/test/java/seedu/address/model/patient/AssignedDepartmentTest.java
  src/test/java/seedu/address/model/patient/IcNumberTest.java
  src/test/java/seedu/address/model/patient/NameTest.java
  src/test/java/seedu/address/model/patient/PriorityTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
Labels: type.Task, type.Bug, priority.High

#227 Branch fix add bugs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/_markbind/layouts/default.md
  docs/team/aaronjt1.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/patient/PatientWithIcNumberPredicateTest.java
Labels: priority.High

#228 Fixed error message bug for assign command and updated PPP
  docs/team/wujy28.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Task, type.Bug

#233 Update use cases in DeveloperGuide
  docs/DeveloperGuide.md
  docs/team/aaronjt1.md
Labels: priority.High

#240 Branch update ug
  docs/UserGuide.md
  docs/images/ug/addPatients.png
  docs/images/ug/viewPatient.png
  docs/team/aaronjt1.md
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.High

#245 Improve test coverage
  docs/team/aaronjt1.md
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.High

#265 Update single line in PPP
  docs/team/aaronjt1.md
Labels: priority.High
