Repository AY2324S1-CS2103T-T14-2/tp, pull requests merged in 2023-10, with the labels that each got.

#47 Update UserGuide.md
  docs/UserGuide.md
Labels: priority.High

#51 Update User Guide
  docs/UserGuide.md
Labels: priority.High

#52 Update DeveloperGuide.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: priority.High

#77 Add Age and Gender Attributes
  src/main/java/seedu/address/model/patient/Age.java
  src/main/java/seedu/address/model/patient/Gender.java
  src/test/java/seedu/address/model/patient/AgeTest.java
  src/test/java/seedu/address/model/patient/GenderTest.java
Labels: priority.High

#86 Add Record attribute and JUnit tests
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Record.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/java/seedu/address/model/patient/RecordTest.java
  src/test/java/seedu/address/testutil/RecordBuilder.java
Labels: priority.High

#78 Update Add Command to allow required and optional fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.High

#98 Update Record.java and RecordTest.java
  src/main/java/seedu/address/model/patient/Record.java
  src/test/java/seedu/address/model/patient/RecordTest.java
  src/test/java/seedu/address/testutil/RecordBuilder.java
Labels: priority.High

#96 Edit Patient and CliSyntax classes to include new attributes
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/patient/Patient.java
Labels: priority.High

#102 Branch update patient fields
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/Age.java
  src/main/java/seedu/address/model/patient/Birthday.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/Gender.java
  src/main/java/seedu/address/model/patient/IcNumber.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/main/java/seedu/address/model/patient/Record.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/RecordBuilder.java
Labels: priority.High

#103 Update EditCommand.java, EditCommandParser.java, and ParserUtil.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High

#104 Update AddCommandParser to integrate ParserUtil
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/patient/Birthday.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Record.java
Labels: priority.High

#108 Fix Issues in Edit Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/patient/Address.java
  src/main/java/seedu/address/model/patient/Age.java
  src/main/java/seedu/address/model/patient/Birthday.java
  src/main/java/seedu/address/model/patient/Email.java
  src/main/java/seedu/address/model/patient/Gender.java
  src/main/java/seedu/address/model/patient/IcNumber.java
  src/main/java/seedu/address/model/patient/Phone.java
  src/main/java/seedu/address/model/patient/Record.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/RecordBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.High

#112 Integrate assignedDepartment display
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Record.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
Labels: priority.High

#116 Update testing utilities with new Patient attributes
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/patient/Record.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.High

#119 Create view command
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/patient/PatientWithIcNumberPredicate.java
  src/main/java/seedu/address/model/patient/exceptions/PatientWithFieldNotFoundException.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/patient/PatientWithIcNumberPredicateTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.High

#128 Update Add command to check for existing Ic Number
  build.gradle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Enhancement

#137 Update DG with Assign Department Feature and Ui Component
  docs/DeveloperGuide.md
  docs/diagrams/AssignSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: type.Task

#133 Implement Record Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/RecordCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RecordCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RecordCommandTest.java
  src/test/java/seedu/address/testutil/EditRecordDescriptorBuilder.java
Labels: priority.High

#135 Add Assign Department Functionality to App
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/PatientWithIcNumberPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: type.Story, priority.High

#150 Update GUI to look like our final product
  src/main/java/seedu/address/model/patient/Record.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/RecordCard.java
  src/main/java/seedu/address/ui/RecordPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/fonts/Doppio_One/DoppioOne-Regular.ttf
  src/main/resources/fonts/Doppio_One/OFL.txt
  src/main/resources/fonts/Inter/Inter-VariableFont_slnt,wght.ttf
  src/main/resources/fonts/Inter/OFL.txt
  src/main/resources/fonts/Inter/README.txt
  src/main/resources/fonts/Inter/static/Inter-Black.ttf
  src/main/resources/fonts/Inter/static/Inter-Bold.ttf
  src/main/resources/fonts/Inter/static/Inter-ExtraBold.ttf
  src/main/resources/fonts/Inter/static/Inter-ExtraLight.ttf
  src/main/resources/fonts/Inter/static/Inter-Light.ttf
  src/main/resources/fonts/Inter/static/Inter-Medium.ttf
  src/main/resources/fonts/Inter/static/Inter-Regular.ttf
  src/main/resources/fonts/Inter/static/Inter-SemiBold.ttf
  src/main/resources/fonts/Inter/static/Inter-Thin.ttf
  src/main/resources/fonts/Space_Grotesk/OFL.txt
  src/main/resources/fonts/Space_Grotesk/README.txt
  src/main/resources/fonts/Space_Grotesk/SpaceGrotesk-VariableFont_wght.ttf
  src/main/resources/fonts/Space_Grotesk/static/SpaceGrotesk-Bold.ttf
  src/main/resources/fonts/Space_Grotesk/static/SpaceGrotesk-Light.ttf
  src/main/resources/fonts/Space_Grotesk/static/SpaceGrotesk-Medium.ttf
  src/main/resources/fonts/Space_Grotesk/static/SpaceGrotesk-Regular.ttf
  src/main/resources/fonts/Space_Grotesk/static/SpaceGrotesk-SemiBold.ttf
  src/main/resources/images/AELogo.png
  src/main/resources/images/Advanced&Efficient.png
  src/main/resources/view/CommandBox.css
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PatientCard.css
  src/main/resources/view/PatientListCard.fxml
  src/main/resources/view/PatientListPanel.css
  src/main/resources/view/PatientListPanel.fxml
  src/main/resources/view/RecordCard.css
  src/main/resources/view/RecordCard.fxml
  src/main/resources/view/RecordPanel.fxml
  src/main/resources/view/ResultDisplay.css
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: type.Enhancement, priority.Medium

#153 Update commands to show error message if field does not exist
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RecordCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/RecordCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/RecordCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RecordCommandParserTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: type.Enhancement, priority.High
